services:
  api:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8002:8080"
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d datingapp"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: datingapp
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: